from sys import platform
from os import system
from time import sleep
def clear(): 
  if platform == 'win32':
    sytem('cls')
  else:
    system('clear')
    
if True:
  print('( •_•) hi')
  sleep(1)
  clear()
  print('( •_•) sunglasses?')
  sleep(1)
  clear()
  print('( •_•)>⌐■-■')
  sleep(0.1)
  clear()
  print('( •_>⌐■-■')
  sleep(0.1)
  clear()
  print('(⌐■_■)')
  sleep(1)
  clear()
  print('(⌐■_■) nope')
  sleep(1)
  clear()
  print('( •_>⌐■-■')
  sleep(0.1)
  clear()
  print('( •_•)>⌐■-■ ')
  sleep(0.1)
  clear() 
  print('( •_•)')
  sleep(2)
  clear() 
  print('~( •~•)~')
  sleep(1)
  clear() 
  print('-( •~•)-')
  sleep(1)
  clear() 
  print('~( •~•)~ !what')
  sleep(1)
  clear() 
  print('  ~( •~•)~')
  sleep(0.4)
  clear() 
  print('     ~( •~•)~')
  sleep(0.4)
  clear() 
  print('          ~( •~•)~')
  sleep(0.4)
  clear()
  print('                   ~( •~•)~')
  sleep(0.4)
  clear() 
  print('                            ~( •~•)~')
  sleep(0.4)
  clear() 
  print('                                     ~( •~•)~')
  sleep(0.4)
  clear() 
  print("Welcome to Linda's Menu")
  sleep(3)
  clear() 


if __name__ == "__main__":
    clear()